Add tutorial for arbitrary precision in ADNLPModels
JuliaSmoothOptimizers/JSOTutorials.jl pull request #43
Opened 2023-01-27 14:29 UTC by tmigot

**New tutorial**
Tutorial name: Multiprecision and genericity in NLPModels with automatic differentiation

2023-01-27 23:01 UTC, abelsiqueira requested changes
Thanks for the new tutorial, Tangi. I had some issues understanding what was the focus of the tutorial because I did not get the issue that this was trying to solve. I made some comments and suggestions to try to make it clear.
One issue, that is not this tutorial's problem, is that even if we create the multi-precision capable model, we still can't use it in a multi-precision algorithm, i.e., `lbfgs` with `nlp{Float64}` and `x::Float32`.

2023-01-30 15:07 UTC, tmigot commented on tutorials/generic-adnlpmodels/index.jmd
> +# Multiprecision and genericity in NLPModels with automatic differentiation
I changed it for `Creating an ADNLPModels backend that supports multiple types`

2023-01-30 15:07 UTC, tmigot commented on tutorials/generic-adnlpmodels/index.jmd
> +This package is modular in the sense that it implements a backend system allowing the user to use essentially any AD system available, see [ADNLPModels.jl/dev/backend/](https://juliasmoothoptimizers.
Sure, it is possible

2023-01-30 15:09 UTC, tmigot commented
Thanks for the comments @abelsiqueira . 

I added a more detailed introduction to the problem.

About the solvers, it is mainly a JSO-internal issue right now. Several students/postdocs are working on multi-precision algorithms and asked for this feature.

2023-01-30 18:20 UTC, abelsiqueira approved these changes
Thanks for the changes.

2023-02-02 16:49 UTC, d-monnet commented
Thank you for the tutorial, simple and efficient.

I only have a few comments:
- In the [tutorial](https://juliasmoothoptimizers.github.io/JSOTutorials.jl/generic-adnlpmodels/), the Rosenbrock function and initial point are not interpreted correctly.
- Maybe it would worth splitting the  Multiprecision ADNLPModels in two subsections for the sake of clarity: Objective Evaluation and Gradient Evaluation. This would help to emphasized that multi precision evaluation of objective and gradient relies on two different mechanisms (generic typing of x0 and backend).
- It would be nice to have the counters to record the number of eval for each precision that has been used. Not sure how much of a hassle it would be to implement that though.
- In your last example, 
  ```julia
  x16 = Float16.(get_x0(nlp))
  ```
  is typically something I would avoid to do. Casting x0 from Float64 into Float16 implies that rounding error occur, therefore x0 is different than x16 and the gradient is not evaluated as x0. I would keep the example as it is, but point out that issue to the user and mention that one should be extra careful when using multi precision.

2023-02-03 14:40 UTC, tmigot commented
Thanks @d-monnet for the comments, I updated the tuto !

2023-02-03 22:22 UTC, merged

2023-02-03 22:27 UTC, tmigot commented
@d-monnet about counters for multi-precision, I think it would be too much changes for now as I don't really see a simple way. Because right now thé `incrément!` function doesn't have access to thé type.