Bump to ADNLPModels 0.5
JuliaSmoothOptimizers/JSOTutorials.jl pull request #52
Opened 2023-01-31 17:27 UTC by tmigot

In particular, the print of models is fixed with this release.
Test #25

2023-01-31 17:34 UTC, tmigot commented
We actually need to modify the MATRIX https://github.com/JuliaSmoothOptimizers/JSOTutorials.jl/blob/2cdce897c57d284e29c65ff59b6a1a877bec0c81/.github/workflows/Deploy-website.yml#L27 too so that the .jmd file corresponding to the .toml file is added to the list of scripts.

2023-02-07 10:21 UTC, abelsiqueira requested changes
Does this need anything else?

2023-02-07 10:21 UTC, abelsiqueira commented on tutorials/introduction-to-adnlpmodels/Project.toml
> +ADNLPModels = "0.4, 0.5"
```suggestion
ADNLPModels = "0.5"
```
I prefer to use stronger bounds, so there is no doubt that it is using the correct version

2023-02-08 00:56 UTC, tmigot commented
Finally, no more ugly display!

2023-02-08 00:57 UTC, merged